### ISSUE TITLE
Implement AAD auth for Graph APIManifest samples

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/semantic-kernel#28]
Current implementation works with MSA, add an option to make Graph calls work with AAD.

**Comment by peombwa** [comment]
This will involve:
- [ ] Replace `WithTenantId` with `WithAuthority`. MSAL recommends the use of authority (identity provider instance + audience) over tenantId when initializing a client.
- [ ] Configure app registration to be multi-tenant with support for all Microsoft Accounts (Personal + Work and School accounts).
- [ ] Update the sample's appSettings to use the new app registration.

**Comment by peombwa** [comment]
Closing as done.

App settings config has been updated to support all Microsoft accounts.
